=pod

=head1 plot_munger toolbox

Tools for manipulation and plotting of gnuplot-style 3D datafiles

=head2 Features

=over

=item * Simple commandline tool for plotting 3D data with colour plots

=item * Manipulate data with a sequence of operation, e.g. numerical
differentiation

=item * Multitude of plot options: color scales, ranges, etc.

=item * Extract traces along x- or y-axis

=item * Write manipulated data to output datafile

=back

=head2 Installation

To run the scripts, you need python3 with numpy (at least version 1.14.1),
scipy, and matplotlib.

=head3 Installation on Linux

Download the pdfout_tools:

 user $ git clone git://github.com/amba/plot_munger.git


The following assumes a Debian-like Linux system.
Install pip3:

 root # apt-get install pip3
 
Install recent versions of numpy, scipy and matplotlib

 user # pip3 install numpy scipy matplotlib

You should now be able to run the tools

 ./plot_munger.py --help
 ./plot_trace.py --help

=head3 Installation on Windows

See e.g. L<https://solarianprogrammer.com/2017/02/25/install-numpy-scipy-matplotlib-python-3-windows/>

=head2 Quick Start

TODO

=head1 LICENCE

plot_munger is Copyright (C) 2018-2019 by Simon Reinhardt.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

